[package]
name = "file_explorer"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
build = "src/build.rs"

[[bin]]
path = "src/creating_database.rs"
name = "creating_database"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
walkdir = "2.5.0"
strsim = "0.10.0"
threadpool = "1.8.1"
rayon = "1.7.0"
sqlx = { version = "0.8", features = [ "runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.0.134"
unicode-width = "0.2.0"
async-std = "1.13.0"



[build-dependencies]
embed-manifest = "1"





