[package]
name = "file_explorer"
version = "0.1.0"
description = "File Explorer with a fast searching algorithm"
authors = ["you"]
edition = "2021"
build = "src/build.rs"

[[bin]]
path = "src/main.rs"
name = "Semi24-Fileexplorer"

[lib]
name = "file_explorer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
walkdir = "2.5.0"
strsim = "0.10.0"
rayon = "1.10.0"  # Add this line


[build-dependencies]
tauri-build = { version = "2", features = [] }
embed-manifest = "1"

[features]
mobile = []
